services:
  db:
    container_name: greencity-postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER:      admin
      POSTGRES_PASSWORD:  admin
      POSTGRES_DB:        greencity
    ports:
      - "5433:5432"
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
